[PHP]
max_execution_time = 300
max_input_time = 300
memory_limit = 512M
upload_max_filesize = 100M
max_file_uploads = 20
post_max_size = 100M
display_errors = Off
log_errors = On

[opcache]
opcache.enable = 1
opcache.enable_cli = 1
opcache.memory_consumption = 128
opcache.interned_strings_buffer = 8
opcache.max_accelerated_files = 4000
; Tidak perlu cek file changes di production — kode tidak berubah saat runtime
opcache.revalidate_freq = 60
opcache.validate_timestamps = 0
opcache.fast_shutdown = 1
